spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/ffms?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      username: root
      password: root
      #初始化时建立物理连接的个数
      initial-size: 5
      #最小连接池数量
      min-idle: 5
      #最大连接池数量 maxIdle已经不再使用
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: select 'x'
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.xust.ffms.entity

logging:
  level:
    root: info
    org:
      springframework:
        web: info
    com.xust.ffms.dao: debug
server:
  port: 8081
  resources:
    #静态资源扫描
    static-locations: classpath:/WEB-INF/resources/
